# Generated by Django 5.0.1 on 2024-01-18 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(choices=[('F', 'Завод'), ('R', 'Розничная сеть'), ('IE', 'Индивидуальный предприниматель')], max_length=2, verbose_name='Тип организации')),
                ('hierarchy_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Уровень в иерархии')),
                ('name', models.CharField(max_length=50, verbose_name='Название организации')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Долг перед поставщиком')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='shop.contact', verbose_name='Контакты')),
                ('product', models.ManyToManyField(related_name='products', to='shop.product', verbose_name='')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='shop.organization', verbose_name='Поставщик')),
            ],
        ),
    ]
