# Generated by Django 5.0.1 on 2024-01-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_organization_options_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Долг перед поставщиком'),
        ),
    ]
